export enum ImportErrorCode {
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  INVALID_FORMAT = 'INVALID_FORMAT',
  INVALID_JSON = 'INVALID_JSON',
  UNIVERSITY_NOT_FOUND = 'UNIVERSITY_NOT_FOUND',
  AMBIGUOUS_UNIVERSITY = 'AMBIGUOUS_UNIVERSITY',
  UNKNOWN_DEGREE = 'UNKNOWN_DEGREE',
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
  RESOLUTION_FAILED = 'RESOLUTION_FAILED',
  DUPLICATE_ROW = 'DUPLICATE_ROW',
}

export function formatImportError(
  code: ImportErrorCode,
  humanMessage: string,
): string {
  return `${code}: ${humanMessage}`;
}

