export enum ErrorCode {
  DOMAIN_ERROR = 'DOMAIN_ERROR',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  USER_CONFLICT = 'USER_CONFLICT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  BUSINESS_ERROR = 'BUSINESS_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  OTP_PROVIDER_UNAVAILABLE = 'OTP_PROVIDER_UNAVAILABLE',
}

